/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as layoutRouteRouteImport } from './routes/(layout)/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as layoutIndexRouteImport } from './routes/(layout)/index'
import { Route as AdminReviewRouteImport } from './routes/admin/review'
import { Route as AdminQueueRouteImport } from './routes/admin/queue'
import { Route as layoutContributorsRouteImport } from './routes/(layout)/contributors'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as layoutprotectedRouteRouteImport } from './routes/(layout)/(protected)/route'
import { Route as layoutResourcesIndexRouteImport } from './routes/(layout)/resources/index'
import { Route as layoutOpportunitiesIndexRouteImport } from './routes/(layout)/opportunities/index'
import { Route as layoutOpportunitiesIdRouteImport } from './routes/(layout)/opportunities/$id'
import { Route as layoutprotectedSubmissionsRouteImport } from './routes/(layout)/(protected)/submissions'
import { Route as layoutprotectedMySubmissionsRouteImport } from './routes/(layout)/(protected)/my-submissions'
import { Route as layoutResourcesTrainingsIndexRouteImport } from './routes/(layout)/resources/trainings/index'
import { Route as layoutResourcesTemplatesIndexRouteImport } from './routes/(layout)/resources/templates/index'
import { Route as layoutResourcesGuidesIndexRouteImport } from './routes/(layout)/resources/guides/index'
import { Route as layoutResourcesTrainingsIdRouteImport } from './routes/(layout)/resources/trainings/$id'
import { Route as layoutResourcesTemplatesIdRouteImport } from './routes/(layout)/resources/templates/$id'
import { Route as layoutResourcesGuidesSlugRouteImport } from './routes/(layout)/resources/guides/$slug'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const layoutRouteRoute = layoutRouteRouteImport.update({
  id: '/(layout)',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const layoutIndexRoute = layoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => layoutRouteRoute,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminRouteRoute,
} as any)
const layoutContributorsRoute = layoutContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => layoutRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const layoutprotectedRouteRoute = layoutprotectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => layoutRouteRoute,
} as any)
const layoutResourcesIndexRoute = layoutResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => layoutRouteRoute,
} as any)
const layoutOpportunitiesIndexRoute =
  layoutOpportunitiesIndexRouteImport.update({
    id: '/opportunities/',
    path: '/opportunities/',
    getParentRoute: () => layoutRouteRoute,
  } as any)
const layoutOpportunitiesIdRoute = layoutOpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => layoutRouteRoute,
} as any)
const layoutprotectedSubmissionsRoute =
  layoutprotectedSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => layoutprotectedRouteRoute,
  } as any)
const layoutprotectedMySubmissionsRoute =
  layoutprotectedMySubmissionsRouteImport.update({
    id: '/my-submissions',
    path: '/my-submissions',
    getParentRoute: () => layoutprotectedRouteRoute,
  } as any)
const layoutResourcesTrainingsIndexRoute =
  layoutResourcesTrainingsIndexRouteImport.update({
    id: '/resources/trainings/',
    path: '/resources/trainings/',
    getParentRoute: () => layoutRouteRoute,
  } as any)
const layoutResourcesTemplatesIndexRoute =
  layoutResourcesTemplatesIndexRouteImport.update({
    id: '/resources/templates/',
    path: '/resources/templates/',
    getParentRoute: () => layoutRouteRoute,
  } as any)
const layoutResourcesGuidesIndexRoute =
  layoutResourcesGuidesIndexRouteImport.update({
    id: '/resources/guides/',
    path: '/resources/guides/',
    getParentRoute: () => layoutRouteRoute,
  } as any)
const layoutResourcesTrainingsIdRoute =
  layoutResourcesTrainingsIdRouteImport.update({
    id: '/resources/trainings/$id',
    path: '/resources/trainings/$id',
    getParentRoute: () => layoutRouteRoute,
  } as any)
const layoutResourcesTemplatesIdRoute =
  layoutResourcesTemplatesIdRouteImport.update({
    id: '/resources/templates/$id',
    path: '/resources/templates/$id',
    getParentRoute: () => layoutRouteRoute,
  } as any)
const layoutResourcesGuidesSlugRoute =
  layoutResourcesGuidesSlugRouteImport.update({
    id: '/resources/guides/$slug',
    path: '/resources/guides/$slug',
    getParentRoute: () => layoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/contributors': typeof layoutContributorsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/review': typeof AdminReviewRoute
  '/': typeof layoutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/my-submissions': typeof layoutprotectedMySubmissionsRoute
  '/submissions': typeof layoutprotectedSubmissionsRoute
  '/opportunities/$id': typeof layoutOpportunitiesIdRoute
  '/opportunities/': typeof layoutOpportunitiesIndexRoute
  '/resources/': typeof layoutResourcesIndexRoute
  '/resources/guides/$slug': typeof layoutResourcesGuidesSlugRoute
  '/resources/templates/$id': typeof layoutResourcesTemplatesIdRoute
  '/resources/trainings/$id': typeof layoutResourcesTrainingsIdRoute
  '/resources/guides/': typeof layoutResourcesGuidesIndexRoute
  '/resources/templates/': typeof layoutResourcesTemplatesIndexRoute
  '/resources/trainings/': typeof layoutResourcesTrainingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/contributors': typeof layoutContributorsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/review': typeof AdminReviewRoute
  '/': typeof layoutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/my-submissions': typeof layoutprotectedMySubmissionsRoute
  '/submissions': typeof layoutprotectedSubmissionsRoute
  '/opportunities/$id': typeof layoutOpportunitiesIdRoute
  '/opportunities': typeof layoutOpportunitiesIndexRoute
  '/resources': typeof layoutResourcesIndexRoute
  '/resources/guides/$slug': typeof layoutResourcesGuidesSlugRoute
  '/resources/templates/$id': typeof layoutResourcesTemplatesIdRoute
  '/resources/trainings/$id': typeof layoutResourcesTrainingsIdRoute
  '/resources/guides': typeof layoutResourcesGuidesIndexRoute
  '/resources/templates': typeof layoutResourcesTemplatesIndexRoute
  '/resources/trainings': typeof layoutResourcesTrainingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(layout)': typeof layoutRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/(layout)/(protected)': typeof layoutprotectedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(layout)/contributors': typeof layoutContributorsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/review': typeof AdminReviewRoute
  '/(layout)/': typeof layoutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/(layout)/(protected)/my-submissions': typeof layoutprotectedMySubmissionsRoute
  '/(layout)/(protected)/submissions': typeof layoutprotectedSubmissionsRoute
  '/(layout)/opportunities/$id': typeof layoutOpportunitiesIdRoute
  '/(layout)/opportunities/': typeof layoutOpportunitiesIndexRoute
  '/(layout)/resources/': typeof layoutResourcesIndexRoute
  '/(layout)/resources/guides/$slug': typeof layoutResourcesGuidesSlugRoute
  '/(layout)/resources/templates/$id': typeof layoutResourcesTemplatesIdRoute
  '/(layout)/resources/trainings/$id': typeof layoutResourcesTrainingsIdRoute
  '/(layout)/resources/guides/': typeof layoutResourcesGuidesIndexRoute
  '/(layout)/resources/templates/': typeof layoutResourcesTemplatesIndexRoute
  '/(layout)/resources/trainings/': typeof layoutResourcesTrainingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/login'
    | '/signup'
    | '/contributors'
    | '/admin/queue'
    | '/admin/review'
    | '/'
    | '/admin/'
    | '/my-submissions'
    | '/submissions'
    | '/opportunities/$id'
    | '/opportunities/'
    | '/resources/'
    | '/resources/guides/$slug'
    | '/resources/templates/$id'
    | '/resources/trainings/$id'
    | '/resources/guides/'
    | '/resources/templates/'
    | '/resources/trainings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/contributors'
    | '/admin/queue'
    | '/admin/review'
    | '/'
    | '/admin'
    | '/my-submissions'
    | '/submissions'
    | '/opportunities/$id'
    | '/opportunities'
    | '/resources'
    | '/resources/guides/$slug'
    | '/resources/templates/$id'
    | '/resources/trainings/$id'
    | '/resources/guides'
    | '/resources/templates'
    | '/resources/trainings'
  id:
    | '__root__'
    | '/(layout)'
    | '/admin'
    | '/(layout)/(protected)'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(layout)/contributors'
    | '/admin/queue'
    | '/admin/review'
    | '/(layout)/'
    | '/admin/'
    | '/(layout)/(protected)/my-submissions'
    | '/(layout)/(protected)/submissions'
    | '/(layout)/opportunities/$id'
    | '/(layout)/opportunities/'
    | '/(layout)/resources/'
    | '/(layout)/resources/guides/$slug'
    | '/(layout)/resources/templates/$id'
    | '/(layout)/resources/trainings/$id'
    | '/(layout)/resources/guides/'
    | '/(layout)/resources/templates/'
    | '/(layout)/resources/trainings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  layoutRouteRoute: typeof layoutRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(layout)': {
      id: '/(layout)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(layout)/': {
      id: '/(layout)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof layoutIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(layout)/contributors': {
      id: '/(layout)/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof layoutContributorsRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(layout)/(protected)': {
      id: '/(layout)/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layoutprotectedRouteRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/resources/': {
      id: '/(layout)/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof layoutResourcesIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/opportunities/': {
      id: '/(layout)/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof layoutOpportunitiesIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/opportunities/$id': {
      id: '/(layout)/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof layoutOpportunitiesIdRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/(protected)/submissions': {
      id: '/(layout)/(protected)/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof layoutprotectedSubmissionsRouteImport
      parentRoute: typeof layoutprotectedRouteRoute
    }
    '/(layout)/(protected)/my-submissions': {
      id: '/(layout)/(protected)/my-submissions'
      path: '/my-submissions'
      fullPath: '/my-submissions'
      preLoaderRoute: typeof layoutprotectedMySubmissionsRouteImport
      parentRoute: typeof layoutprotectedRouteRoute
    }
    '/(layout)/resources/trainings/': {
      id: '/(layout)/resources/trainings/'
      path: '/resources/trainings'
      fullPath: '/resources/trainings/'
      preLoaderRoute: typeof layoutResourcesTrainingsIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/resources/templates/': {
      id: '/(layout)/resources/templates/'
      path: '/resources/templates'
      fullPath: '/resources/templates/'
      preLoaderRoute: typeof layoutResourcesTemplatesIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/resources/guides/': {
      id: '/(layout)/resources/guides/'
      path: '/resources/guides'
      fullPath: '/resources/guides/'
      preLoaderRoute: typeof layoutResourcesGuidesIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/resources/trainings/$id': {
      id: '/(layout)/resources/trainings/$id'
      path: '/resources/trainings/$id'
      fullPath: '/resources/trainings/$id'
      preLoaderRoute: typeof layoutResourcesTrainingsIdRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/resources/templates/$id': {
      id: '/(layout)/resources/templates/$id'
      path: '/resources/templates/$id'
      fullPath: '/resources/templates/$id'
      preLoaderRoute: typeof layoutResourcesTemplatesIdRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/resources/guides/$slug': {
      id: '/(layout)/resources/guides/$slug'
      path: '/resources/guides/$slug'
      fullPath: '/resources/guides/$slug'
      preLoaderRoute: typeof layoutResourcesGuidesSlugRouteImport
      parentRoute: typeof layoutRouteRoute
    }
  }
}

interface layoutprotectedRouteRouteChildren {
  layoutprotectedMySubmissionsRoute: typeof layoutprotectedMySubmissionsRoute
  layoutprotectedSubmissionsRoute: typeof layoutprotectedSubmissionsRoute
}

const layoutprotectedRouteRouteChildren: layoutprotectedRouteRouteChildren = {
  layoutprotectedMySubmissionsRoute: layoutprotectedMySubmissionsRoute,
  layoutprotectedSubmissionsRoute: layoutprotectedSubmissionsRoute,
}

const layoutprotectedRouteRouteWithChildren =
  layoutprotectedRouteRoute._addFileChildren(layoutprotectedRouteRouteChildren)

interface layoutRouteRouteChildren {
  layoutprotectedRouteRoute: typeof layoutprotectedRouteRouteWithChildren
  layoutContributorsRoute: typeof layoutContributorsRoute
  layoutIndexRoute: typeof layoutIndexRoute
  layoutOpportunitiesIdRoute: typeof layoutOpportunitiesIdRoute
  layoutOpportunitiesIndexRoute: typeof layoutOpportunitiesIndexRoute
  layoutResourcesIndexRoute: typeof layoutResourcesIndexRoute
  layoutResourcesGuidesSlugRoute: typeof layoutResourcesGuidesSlugRoute
  layoutResourcesTemplatesIdRoute: typeof layoutResourcesTemplatesIdRoute
  layoutResourcesTrainingsIdRoute: typeof layoutResourcesTrainingsIdRoute
  layoutResourcesGuidesIndexRoute: typeof layoutResourcesGuidesIndexRoute
  layoutResourcesTemplatesIndexRoute: typeof layoutResourcesTemplatesIndexRoute
  layoutResourcesTrainingsIndexRoute: typeof layoutResourcesTrainingsIndexRoute
}

const layoutRouteRouteChildren: layoutRouteRouteChildren = {
  layoutprotectedRouteRoute: layoutprotectedRouteRouteWithChildren,
  layoutContributorsRoute: layoutContributorsRoute,
  layoutIndexRoute: layoutIndexRoute,
  layoutOpportunitiesIdRoute: layoutOpportunitiesIdRoute,
  layoutOpportunitiesIndexRoute: layoutOpportunitiesIndexRoute,
  layoutResourcesIndexRoute: layoutResourcesIndexRoute,
  layoutResourcesGuidesSlugRoute: layoutResourcesGuidesSlugRoute,
  layoutResourcesTemplatesIdRoute: layoutResourcesTemplatesIdRoute,
  layoutResourcesTrainingsIdRoute: layoutResourcesTrainingsIdRoute,
  layoutResourcesGuidesIndexRoute: layoutResourcesGuidesIndexRoute,
  layoutResourcesTemplatesIndexRoute: layoutResourcesTemplatesIndexRoute,
  layoutResourcesTrainingsIndexRoute: layoutResourcesTrainingsIndexRoute,
}

const layoutRouteRouteWithChildren = layoutRouteRoute._addFileChildren(
  layoutRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminQueueRoute: typeof AdminQueueRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminQueueRoute: AdminQueueRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  layoutRouteRoute: layoutRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
